export const siteConfig = {
  name: "Rishab Kumar - Applied AI Engineer",
  authorName: "Rishab Kumar",
  username: "rishabmahor06",
  description:
    "Rishab Kumar - Applied AI Engineer working at the intersection of AI, data, and scalable software systems. Explore my projects, experience, and contributions in software development and AI.",
  url: "https://rishabmahor06.github.io",
  githubUrl: "https://github.com/rishabmahor06",
  links: {
    twitter: "https://x.com/rishabmahor06",
    github: "https://github.com/rishabmahor06",
    templateRepo: "https://github.com/rishabmahor06/minimal-next-portfolio",
  },
  ogImage:
    "https://res.cloudinary.com/dvt5vkfwz/image/upload/v1767384721/rishab_portfolio_og_image.png",
  iconIco: "/profile-img.jpg",
  logoIcon: "/profile-img.jpg",
  keywords: [
    "Rishab Kumar",
    "Applied AI Engineer",
    "AI Engineer",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
